import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { ThirdwebProvider } from "thirdweb/react";
import { ConfigProvider } from "./builder/context/ConfigContext"; // Import ConfigProvider

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home Landing Page - Inovasi Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThirdwebProvider>
          <ConfigProvider>
            <Navbar />
            {children}
          </ConfigProvider>
        </ThirdwebProvider>
      </body>
    </html>
  );
}
