import { Metadata } from "next";
import Payment from "../components/Payment";

export const metadata: Metadata = {
  title: "Payment Page - Inovasi Web",
  description: "Generated by create next app",
};
const page = () => {
  return <Payment />;
};
export default page;
