// app/page.tsx
import { Metadata } from "next";
import prisma from "../lib/prisma";
import Tema from "../components/Tema";

export const metadata: Metadata = {
  title: "Tema Page - Inovasi Web",
  description: "Generated by create next app",
};

// Fetch data directly in the component
const Page = async () => {
  // Replace '1' with your actual user ID or criteria
  const user = await prisma.user.findUnique({
    where: { id: 1 },
  });

  if (!user) {
    return <p>User not found</p>;
  }

  return (
    <div className="mx-auto mt-24 max-w-[1120px] text-center">
      <p className="text-center text-4xl font-semibold xl:mx-auto xl:w-[760px]">
        Saatnya Bangun Website Untuk Bisnismu Dengan Berbagai Tema Yang Menarik
      </p>
      <p className="pb-10 text-center">
        Pilih salah satu tema dibawah ini untuk mulai membangun websitemu
      </p>
      <div>
        <h2>User Information:</h2>
        <p>Name: {user.name}</p>
        <p>Email: {user.email}</p>
        {/* Render more user information here */}
      </div>
      <Tema />
    </div>
  );
};

export default Page;
