import React from "react";
import Tema from "../components/Tema";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Tema Page - Inovasi Web",
  description: "Generated by create next app",
};
function page() {
  return (
    <div className="mx-auto mt-24 max-w-[1120px] text-center">
      <p className="w-[1000px] text-center text-4xl">
        Saatnya Bangun Website Untuk Bisnismu Dengan Berbagai Tema Yang Menarik
      </p>
      <p className="text-center">
        Pilih salah satu tema dibawah ini untuk mulai membangun websitemu
      </p>
      <Tema />
    </div>
  );
}

export default page;
